security:
  policy:
    permitAllUri:
      - /v2/**
      - /v1/sign-in
      - /v1/sign-up
    servletPrefix: ${spring.mvc.servlet.path}
  jwt:
    accessToken:
      secretKey: helloWorld,access!
      expirationTimeMinute: 5
    refreshToken:
      secretKey: helloWorld,refresh!
      expirationTimeMinute: 10
  encoderSecret: helloWorldEncoderKey1234

spring:
  mvc:
    servlet:
      path: /api

